/* =====================================================================
   5차원 영어 · PATTERN DRILL
   patterns.js — 문장 패턴 학습 데이터

   교재 PATTERN DRILL의 원리:
   영어 문장은 4가지 말 덩어리로 이루어진다 —
   ① 기본 문형(5형식)  ② 형용사(명사 꾸미기)
   ③ 명사(~하는 것)    ④ 부사(~때문에·~할 때)
   교재 PATTERN DRILL MIXED 207문장을 한국어→영어로 익힌다.
   ===================================================================== */

/* --- 4개 그룹 ------------------------------------------------------- */
const PATTERN_GROUPS = [
  { id: 'basic', emoji: '🧱', title: '기본 문형 (5형식)',     desc: '문장의 5가지 뼈대' },
  { id: 'adj',   emoji: '🎀', title: '형용사 · 명사 꾸미기',  desc: '명사를 꾸미는 말 덩어리' },
  { id: 'noun',  emoji: '📦', title: '명사 · ~하는 것',       desc: '주어·목적어가 되는 말 덩어리' },
  { id: 'adv',   emoji: '🧭', title: '부사 · ~때문에·~할 때', desc: '문장을 꾸미는 말 덩어리' },
];

/* --- 22개 패턴 ------------------------------------------------------ */
const PATTERNS = [
  { id: 'p1', group: 'basic', label: '1형식 · 주어+동사',              note: 'N V' },
  { id: 'p2', group: 'basic', label: '2형식 · 주어+동사+보어',         note: 'N V A/N' },
  { id: 'p3', group: 'basic', label: '3형식 · 주어+동사+목적어',       note: 'N V N' },
  { id: 'p4', group: 'basic', label: '4형식 · 주어+동사+간·직목적어',  note: 'N V N N' },
  { id: 'p5', group: 'basic', label: '5형식 · 주어+동사+목적어+보어',  note: 'N V N A/N' },

  { id: 'a1', group: 'adj', label: '전치사구 수식',  note: 'N + 전치사 + N' },
  { id: 'a2', group: 'adj', label: 'to부정사 수식',  note: 'N + to V' },
  { id: 'a3', group: 'adj', label: '현재분사 수식',  note: 'N + V-ing' },
  { id: 'a4', group: 'adj', label: '과거분사 수식',  note: 'N + V-ed' },
  { id: 'a5', group: 'adj', label: '관계절 수식',    note: 'N + that S V' },

  { id: 'n1', group: 'noun', label: '동명사',     note: 'V-ing' },
  { id: 'n2', group: 'noun', label: 'to부정사',   note: 'to V' },
  { id: 'n3', group: 'noun', label: 'that절',     note: 'that S V' },
  { id: 'n4', group: 'noun', label: 'what절',     note: 'what S V' },
  { id: 'n5', group: 'noun', label: '의문사절',   note: '의문사 S V' },
  { id: 'n6', group: 'noun', label: 'whether절',  note: 'whether S V' },

  { id: 'd1', group: 'adv', label: '이유 · ~때문에·~해서',  note: 'because / V-ing' },
  { id: 'd2', group: 'adv', label: '분사구문 · ~되어서',    note: 'V-ed' },
  { id: 'd3', group: 'adv', label: '목적 · ~하기 위해서',   note: 'to V' },
  { id: 'd4', group: 'adv', label: '시간 · ~할 때',         note: 'when / while / after' },
  { id: 'd5', group: 'adv', label: '양보 · 비록 ~지만',     note: 'though' },
  { id: 'd6', group: 'adv', label: '조건·가정 · 만약 ~라면', note: 'if' },
];

/* --- 교재 PATTERN DRILL MIXED 207문장 ------------------------------ */
/* { ko: 한국어, en: 영어, p: 패턴 id }                               */
const SENTENCES = [
  { ko: 'Edison에 의해 발명된 축음기', en: 'the gramophone invented by Edison', p: 'a4' },
  { ko: 'Mike에 의해 그려진 캐리커쳐', en: 'the caricature drawn by Mike', p: 'a4' },
  { ko: 'Mike에 의해 쓰여진 기사', en: 'the article written by Mike', p: 'a4' },
  { ko: 'Sally가 그녀의 박스를 열게 만들기 위해서', en: 'to make Sally open her box', p: 'd3' },
  { ko: 'Sarah가 그 소녀를 꾸중했기 때문에', en: 'because Sarah scolded the girl', p: 'd1' },
  { ko: 'Sarah가 그를 싫어했기 때문에', en: 'because Sarah disliked him', p: 'd1' },
  { ko: 'Tina는 놀랐습니다.', en: 'Tina was surprised.', p: 'p2' },
  { ko: 'Tom은 매우 피곤해요.', en: 'Tom is very tired.', p: 'p2' },
  { ko: 'Tom이 그의 선생님을 보자마자', en: 'as soon as Tom saw his teacher', p: 'd4' },
  { ko: '가난했기 때문에', en: 'because he was poor', p: 'd1' },
  { ko: '강하고 건강하게 자랄 아이들', en: 'children who will grow up strong and healthy', p: 'a5' },
  { ko: '걔네들은 매일 친구들을 만나니?', en: 'Do they meet their friends every day?', p: 'p3' },
  { ko: '거리로 걸어나갈 때', en: 'when you walk out into the street', p: 'd4' },
  { ko: '그 강에서 수영하고 있는 몇 아이들', en: 'some children swimming in the river', p: 'a3' },
  { ko: '그 강은 말라 갑니다.', en: 'The river is drying up.', p: 'p1' },
  { ko: '그 농부는 이른 아침부터 쭉 일해오고 있다.', en: 'The farmer has been working since early morning.', p: 'p1' },
  { ko: '그 돈을 훔칠 것', en: 'to steal the money', p: 'n2' },
  { ko: '그 빨간 머리의 여자아이', en: 'the girl with red hair', p: 'a1' },
  { ko: '그 사람에게로 이동하고 있는 한 마리의 개', en: 'a dog moving toward the man', p: 'a3' },
  { ko: '그 아기의 엄마는 항상 미소짓습니다.', en: "The baby's mother always smiles.", p: 'p1' },
  { ko: '그 약속을 지키는 것', en: 'keeping the promise', p: 'n1' },
  { ko: '그 정보를 모으는 것', en: 'gathering the information', p: 'n1' },
  { ko: '그 줄에서 기다리고 있었던 첫번째 사람', en: 'the first person who was waiting in line', p: 'a5' },
  { ko: '그 집 바깥에 주차된 큰 빨간 차 한대', en: 'a big red car parked outside the house', p: 'a4' },
  { ko: '그 파티에 초대되어졌기 때문에', en: 'because he was invited to the party', p: 'd1' },
  { ko: '그가 나를 생각하게 만드는지 아닌지', en: 'whether he makes me think or not', p: 'n6' },
  { ko: '그가 나무들을 심었는지를', en: 'whether he planted the trees', p: 'n6' },
  { ko: '그가 나에 대해서 말했던 것', en: 'what he said about me', p: 'n4' },
  { ko: '그가 나에게 중요한 교훈을 가르쳐 주었는지 아닌지', en: 'whether he taught me an important lesson or not', p: 'n6' },
  { ko: '그가 늦잠을 자는지 아닌지', en: 'whether he sleeps late or not', p: 'n6' },
  { ko: '그가 아팠기 때문에', en: 'because he was sick', p: 'd1' },
  { ko: '그가 열심히 공부했기 때문에', en: 'because he studied hard', p: 'd1' },
  { ko: '그가 일을 끝내고 나서', en: 'after he finished the work', p: 'd4' },
  { ko: '그것들 사이에 있는 나무', en: 'the tree between them', p: 'a1' },
  { ko: '그녀가 당신에게 당신의 성공을 기원해줬어요.', en: 'She wished you success.', p: 'p4' },
  { ko: '그녀가 배드민턴을 친다는 사실', en: 'the fact that she plays badminton', p: 'n3' },
  { ko: '그녀는 나에게 우편엽서를 보냈다.', en: 'She sent me a postcard.', p: 'p4' },
  { ko: '그녀는 아이들에게 춤을 가르쳐 왔다.', en: 'She has taught children how to dance.', p: 'p4' },
  { ko: '그녀는 어제 학교에 도착했다.', en: 'She got to school yesterday.', p: 'p3' },
  { ko: '그녀가 엄마를 보자마자', en: 'as soon as she saw her mother', p: 'd4' },
  { ko: '그녀는 점차 피곤해졌습니다.', en: 'She gradually became tired.', p: 'p2' },
  { ko: '그녀에 의해 설득당해서', en: 'persuaded by her', p: 'd2' },
  { ko: '그녀의 모습이 담긴 사진 한 장', en: 'a photo containing her image', p: 'a3' },
  { ko: '그녀의 집 근처에 살지만', en: 'though he lives near her house', p: 'd5' },
  { ko: '그는 내가 생각하게 만듭니다.', en: 'He makes me think.', p: 'p5' },
  { ko: '그는 무언가를 발견했습니다.', en: 'He discovered something.', p: 'p3' },
  { ko: '그는 미쳐 갔습니다.', en: 'He went crazy.', p: 'p2' },
  { ko: '그는 행복하곤 했다.', en: 'He used to be happy.', p: 'p2' },
  { ko: '그는 회의에 참석했다.', en: 'He attended the meeting.', p: 'p3' },
  { ko: '그들에게 편지를 보내기 위해서', en: 'to send them a letter', p: 'd3' },
  { ko: '그들은 거기로 걸어갈 겁니다.', en: 'They will walk there.', p: 'p1' },
  { ko: '그들은 그 물을 마실 계획이다.', en: 'They plan to drink the water.', p: 'p3' },
  { ko: '그들은 나에게 사과를 좀 남겨주었다.', en: 'They left me some apples.', p: 'p4' },
  { ko: '그들은 매우 빠르다.', en: 'They are very fast.', p: 'p2' },
  { ko: '그들이 먹고 있었던 것', en: 'what they were eating', p: 'n4' },
  { ko: '그들이 하곤 했던 것', en: 'what they used to do', p: 'n4' },
  { ko: '그를 만나기 위해서', en: 'to meet him', p: 'd3' },
  { ko: '그를 설득하는 것', en: 'persuading him', p: 'n1' },
  { ko: '끝내야 할 숙제', en: 'the homework to finish', p: 'a2' },
  { ko: '나는 그 문이 열리게 두었습니다.', en: 'I left the door open.', p: 'p5' },
  { ko: '나는 그가 유죄라는 것을 알았다.', en: 'I knew that he was guilty.', p: 'p3' },
  { ko: '나는 그것이 어렵다는 것을 알았다.', en: 'I found that it was difficult.', p: 'p3' },
  { ko: '나는 네가 내 차를 운전했으면 해.', en: 'I want you to drive my car.', p: 'p5' },
  { ko: '나는 매일 수영해요.', en: 'I swim every day.', p: 'p1' },
  { ko: '내가 아무런 돈도 없었다는 사실', en: 'the fact that I had no money', p: 'n3' },
  { ko: '나는 울었다.', en: 'I cried.', p: 'p1' },
  { ko: '나를 기다리고 있는 사람들', en: 'the people who are waiting for me', p: 'a5' },
  { ko: '나를 생각하게 만들기 위해서', en: 'to make me think', p: 'd3' },
  { ko: '나를 좋아하는 그 선생님', en: 'the teacher who likes me', p: 'a5' },
  { ko: '나무 아래서 쉬기 위해서', en: 'to rest under the tree', p: 'd3' },
  { ko: '나에게 길을 알려준 소년', en: 'the boy who showed me the way', p: 'a5' },
  { ko: '나에게 꽃을 보낸 그 여인', en: 'the lady who sent me flowers', p: 'a5' },
  { ko: '나에게 소리 지르고 있는 사람들', en: 'the people who are shouting at me', p: 'a5' },
  { ko: '나의 딸에게 나의 시계를 주는 것', en: 'giving my watch to my daughter', p: 'n1' },
  { ko: '나의 아버지는 저에게 책을 읽어주곤 했죠.', en: 'My father used to read me books.', p: 'p4' },
  { ko: '나의 아빠가 Brown씨 가족을 초대하셨다는 사실', en: 'the fact that my dad invited the Browns', p: 'n3' },
  { ko: '나의 인생을 비춰줄 그 사람', en: 'the person who will light up my life', p: 'a5' },
  { ko: '나의 질문에 답하기', en: 'answering my question', p: 'n1' },
  { ko: '날씨가 너무 좋았기 때문에', en: 'because the weather was so nice', p: 'd1' },
  { ko: '날카로운 칼에 베여서', en: 'cut by a sharp knife', p: 'd2' },
  { ko: '낡은 옷과 접시를 팔려고', en: 'to sell old clothes and dishes', p: 'd3' },
  { ko: '내 옆에 서있는 그 남자', en: 'the man standing next to me', p: 'a3' },
  { ko: '내가 가장 싫어하는 과목', en: 'the subject I hate the most', p: 'a5' },
  { ko: '내가 교실에 들어갔을 때', en: 'when I entered the classroom', p: 'd4' },
  { ko: '내가 구해주었던 그 남자', en: 'the man I saved', p: 'a5' },
  { ko: '내가 그 광고를 보았는지를', en: 'whether I saw the advertisement', p: 'n6' },
  { ko: '내가 그것을 들어본 적이 있는지를', en: 'whether I have heard of it', p: 'n6' },
  { ko: '내가 그녀를 만나면', en: 'if I meet her', p: 'd6' },
  { ko: '내가 그녀를 부르자마자', en: 'as soon as I called her', p: 'd4' },
  { ko: '내가 너무 많이 먹으면', en: 'if I eat too much', p: 'd6' },
  { ko: '내가 너에게 얘기했던 그 녀석', en: 'the guy I told you about', p: 'a5' },
  { ko: '내가 사고 싶은 것', en: 'what I want to buy', p: 'n4' },
  { ko: '내가 수영하고 있었던 동안에', en: 'while I was swimming', p: 'd4' },
  { ko: '내가 수영할 때', en: 'when I swim', p: 'd4' },
  { ko: '내가 어제 만났던 사람', en: 'the person I met yesterday', p: 'a5' },
  { ko: '내가 어젯밤에 보았던 그 TV 프로그램', en: 'the TV program I watched last night', p: 'a5' },
  { ko: '내가 영어를 배우고 있다는 사실', en: 'the fact that I am learning English', p: 'n3' },
  { ko: '내가 운전면허증을 가지고 있는지 아닌지', en: "whether I have a driver's license or not", p: 'n6' },
  { ko: '내가 원하는 것', en: 'what I want', p: 'n4' },
  { ko: '내가 위해서 일하는 그 남자', en: 'the man I work for', p: 'a5' },
  { ko: '내가 입은 것', en: 'what I wore', p: 'n4' },
  { ko: '내가 좋아하는 그 선생님', en: 'the teacher I like', p: 'a5' },
  { ko: '내가 파티에서 만났던 그 녀석', en: 'the guy I met at the party', p: 'a5' },
  { ko: '내년에 유학가는 것', en: 'studying abroad next year', p: 'n1' },
  { ko: '너는 너의 아버지를 닮았다.', en: 'You resemble your father.', p: 'p3' },
  { ko: '너는 부지런해.', en: 'You are diligent.', p: 'p2' },
  { ko: '네가 조심히 운전하는 한', en: 'as long as you drive carefully', p: 'd6' },
  { ko: '누가 그 편지를 썼는지', en: 'who wrote the letter', p: 'n5' },
  { ko: '누가 나를 만나고 싶어했는지', en: 'who wanted to meet me', p: 'n5' },
  { ko: '누가 나에게 기회를 줄 수 있는지', en: 'who can give me a chance', p: 'n5' },
  { ko: '눈과 얼음이 그 강을 덮으면', en: 'if snow and ice cover the river', p: 'd6' },
  { ko: '다른 문화에 대한 TV 프로그램', en: 'a TV program about other cultures', p: 'a1' },
  { ko: '당신은 언제 아이들에게 선물을 주나요?', en: 'When do you give the children presents?', p: 'p4' },
  { ko: '당신의 부모님을 이해하는 것', en: 'understanding your parents', p: 'n1' },
  { ko: '당신의 주인이 그를 사면', en: 'if your master buys him', p: 'd6' },
  { ko: '당신이 살 수 있는 것', en: 'what you can buy', p: 'n4' },
  { ko: '당신이 아이들에게 선물을 준다는 사실', en: 'the fact that you give presents to the children', p: 'n3' },
  { ko: '당신이 오른쪽으로 돌면', en: 'if you turn right', p: 'd6' },
  { ko: '당신이 저것을 할 수 있다는 사실', en: 'the fact that you can do that', p: 'n3' },
  { ko: '대통령으로 선출된 후에', en: 'after being elected president', p: 'd4' },
  { ko: '도쿄에 있는 한 회사', en: 'a company in Tokyo', p: 'a1' },
  { ko: '돌려주기로 결정하는 것', en: 'deciding to give it back', p: 'n1' },
  { ko: '돌볼 아이들', en: 'children to take care of', p: 'a2' },
  { ko: '만약 그가 과학을 가르친다면', en: 'if he teaches science', p: 'd6' },
  { ko: '만약 내가 다시 태어난다면', en: 'if I were born again', p: 'd6' },
  { ko: '만약 내가 억만장자라면', en: 'if I were a billionaire', p: 'd6' },
  { ko: '만약 내가 큰 도시에 산다면', en: 'if I lived in a big city', p: 'd6' },
  { ko: '만약에 그가 그녀를 10년 전에 만났더라면', en: 'if he had met her ten years ago', p: 'd6' },
  { ko: '만약에 그들이 나를 만나지 못했었더라면', en: 'if they had not met me', p: 'd6' },
  { ko: '만약에 그들이 나를 못 만났더라면', en: 'if they had not met me', p: 'd6' },
  { ko: '만약에 내가 그 말을 너에게 할 수 있다면', en: 'if I could say that to you', p: 'd6' },
  { ko: '만약에 내가 그녀라면', en: 'if I were her', p: 'd6' },
  { ko: '만약에 내가 안전하게 운전했었더라면', en: 'if I had driven safely', p: 'd6' },
  { ko: '만약에 내가 영어를 그 때 배우지 않았더라면', en: 'if I had not learned English then', p: 'd6' },
  { ko: '만약에 내가 충분히 부자라면', en: 'if I were rich enough', p: 'd6' },
  { ko: '만약에 당신이 지난 3년 동안 나를 도와주지 않았더라면', en: 'if you had not helped me over those three years', p: 'd6' },
  { ko: '만약에 댐이 건설되었더라면', en: 'if the dam had been built', p: 'd6' },
  { ko: '만약에 우리가 그 알람을 맞춰놓지 않았더라면', en: 'if we had not set the alarm', p: 'd6' },
  { ko: '만약에 지금 우리가 여기에 없다면', en: 'if we were not here now', p: 'd6' },
  { ko: '많은 친구들을 갖는 것', en: 'having many friends', p: 'n1' },
  { ko: '매우 피곤하기 때문에', en: 'because I am very tired', p: 'd1' },
  { ko: '매일 친구들을 만나는 것', en: 'to meet friends every day', p: 'n2' },
  { ko: '모든 이들에게 사랑받는 그 사람들', en: 'the people loved by everyone', p: 'a4' },
  { ko: '뭐라 말할지 몰라서', en: 'not knowing what to say', p: 'd1' },
  { ko: '방안에 있는 아이', en: 'the child in the room', p: 'a1' },
  { ko: '병원에 실려 간 그 사람들', en: 'the people carried to the hospital', p: 'a4' },
  { ko: '부드럽게 노래하고 있는 그녀', en: 'the one singing softly', p: 'a3' },
  { ko: '비록 그가 그녀의 집 근처에 살고 있었지만', en: 'though he was living near her house', p: 'd5' },
  { ko: '비록 그것이 중도에 포기하는 것처럼 보이지만', en: 'though it seems like giving up halfway', p: 'd5' },
  { ko: '비록 그녀는 노래부르는 연습을 할 수 있지만', en: 'though she can practice singing', p: 'd5' },
  { ko: '비록 그들이 그 도시를 볼 수 있을지라도', en: 'though they can see the city', p: 'd5' },
  { ko: '비록 그들이 영어를 잘 한다하더라도', en: 'though they speak English well', p: 'd5' },
  { ko: '비록 내가 그녀를 부른다고 할지라도', en: 'though I call her', p: 'd5' },
  { ko: '비록 내가 매일 친구들을 만나지만', en: 'though I meet friends every day', p: 'd5' },
  { ko: '비록 우리가 같은 장소에서 일하지만', en: 'though we work at the same place', p: 'd5' },
  { ko: '사람들이 그것을 팔았기 때문에', en: 'because people sold it', p: 'd1' },
  { ko: '사전에서 단어를 찾기 위해서', en: 'to look up a word in the dictionary', p: 'd3' },
  { ko: '사진 찍는 것', en: 'taking pictures', p: 'n1' },
  { ko: '새들이 노래한다.', en: 'Birds sing.', p: 'p1' },
  { ko: '생각해 봐야할 문제', en: 'a problem to think about', p: 'a2' },
  { ko: '샤워를 하는 것', en: 'taking a shower', p: 'n1' },
  { ko: '샤워하려고', en: 'to take a shower', p: 'd3' },
  { ko: '수영하는 것', en: 'swimming', p: 'n1' },
  { ko: '시 읽을 법 (시를 읽는 방법)', en: 'how to read a poem', p: 'n5' },
  { ko: '시간이 납니다. (세월은 날아가듯 지나간다.)', en: 'Time flies.', p: 'p1' },
  { ko: '아래층에 사는 그 사람들', en: 'the people who live downstairs', p: 'a5' },
  { ko: '안경을 쓴 친구들', en: 'friends wearing glasses', p: 'a3' },
  { ko: '어디서 그가 나에게 점심을 사 주었는지', en: 'where he bought me lunch', p: 'n5' },
  { ko: '어제 해고당했기 때문에', en: 'because I was fired yesterday', p: 'd1' },
  { ko: '언제 그가 John에게 그의 방을 보여줄 수 있는지', en: 'when he can show John his room', p: 'n5' },
  { ko: '언제 내가 아이들에게 선물을 주는지', en: 'when I give presents to the children', p: 'n5' },
  { ko: '엄마에게 꾸중들은 그 소녀', en: 'the girl scolded by her mother', p: 'a4' },
  { ko: '여러 해가 지났다.', en: 'Many years have passed.', p: 'p1' },
  { ko: '영어로 일기를 쓰는 것', en: 'keeping a diary in English', p: 'n1' },
  { ko: '영어를 잘 말하는 그 여자', en: 'the woman who speaks English well', p: 'a5' },
  { ko: '오른쪽으로 돌면', en: 'if you turn right', p: 'd6' },
  { ko: '왜 그가 요리하기를 좋아하는지', en: 'why he likes to cook', p: 'n5' },
  { ko: '왜 내가 그녀에게 공책을 줘야하는지', en: 'why I have to give her a notebook', p: 'n5' },
  { ko: '요리하는 것을 좋아하는 학생', en: 'a student who likes cooking', p: 'a5' },
  { ko: '우리가 6에서 8잔의 물을 마셔야 한다는 사실', en: 'the fact that we have to drink six to eight glasses of water', p: 'n3' },
  { ko: '우리가 그 결정을 내리자마자', en: 'as soon as we made the decision', p: 'd4' },
  { ko: '우리가 그 책을 보면', en: 'if we look at the book', p: 'd6' },
  { ko: '우리가 반바지를 입고 있었다는 사실', en: 'the fact that we were wearing shorts', p: 'n3' },
  { ko: '우리가 보고 싶은 것', en: 'what we want to see', p: 'n4' },
  { ko: '우리가 음식을 요리하면', en: 'if we cook food', p: 'd6' },
  { ko: '우리가 한국인이기 때문에', en: 'because we are Korean', p: 'd1' },
  { ko: '우리는 그 책을 본 적이 없습니다.', en: 'We have never seen the book.', p: 'p3' },
  { ko: '우리는 그것을 아파트라고 부릅니다.', en: 'We call it an apartment.', p: 'p5' },
  { ko: '우리는 그를 의장으로 선출했다.', en: 'We elected him chairman.', p: 'p5' },
  { ko: '우리는 어린이들이 자라는 것을 보았습니다.', en: 'We watched the children grow.', p: 'p5' },
  { ko: '우리들이 그의 친구를 만났는지 아닌지', en: 'whether we met his friend or not', p: 'n6' },
  { ko: '음악을 들으면서', en: 'while listening to music', p: 'd4' },
  { ko: '의사들에 의해 치료되어서', en: 'treated by the doctors', p: 'd2' },
  { ko: '이제 그들이 마침내 나를 만났으니까', en: 'now that they have finally met me', p: 'd4' },
  { ko: '저 경찰이 도둑을 잡았다.', en: 'That policeman caught the thief.', p: 'p3' },
  { ko: '저에게 펜을 하나 빌려주시겠습니까?', en: 'Will you lend me a pen?', p: 'p4' },
  { ko: '중도에 포기하는 것', en: 'giving up halfway', p: 'n1' },
  { ko: '차에 치였음에도 불구하고', en: 'despite being hit by a car', p: 'd5' },
  { ko: '축구 시합 중에 다친 선수', en: 'the player injured during the soccer match', p: 'a4' },
  { ko: '큰소리로 울고 있는 그 남자', en: 'the man crying loudly', p: 'a3' },
  { ko: '테니스를 치는 동안에', en: 'while playing tennis', p: 'd4' },
  { ko: '학생들은 나에게 몇 가지 질문을 했다.', en: 'The students asked me some questions.', p: 'p4' },
  { ko: '한 버스를 타고 있는 무리들', en: 'the crowd riding the bus', p: 'a3' },
  { ko: '한 팀으로서의 노력', en: 'the team effort', p: 'a1' },
  { ko: '한국을 상대로 한 위협', en: 'a threat against Korea', p: 'a1' },
  { ko: '함께 놀 친구들', en: 'friends to play with', p: 'a2' },
  { ko: '홀로 남겨졌을 때', en: 'when you are left alone', p: 'd4' },
];

/* --- 카드 생성 ------------------------------------------------------ */
/* 한 패턴에 속한 문장들을 카드 묶음으로 (교재 순서 그대로).
   섞을지 여부는 드릴 시작 시 설정에 따라 app.js에서 결정한다. */
function buildPatternDeck(patternId) {
  const pat = PATTERNS.find(p => p.id === patternId);
  return SENTENCES
    .filter(s => s.p === patternId)
    .map(s => ({ ko: s.ko, en: s.en, hint: pat ? pat.label : '' }));
}

/* 한 패턴의 문장 개수 */
function patternCount(patternId) {
  return SENTENCES.filter(s => s.p === patternId).length;
}

window.PATTERN = { PATTERN_GROUPS, PATTERNS, SENTENCES, buildPatternDeck, patternCount };
